image: registry.gitlab.isc.org/isc-projects/stork/ci-base:latest

variables:
  POSTGRES_ADDR: postgres:5432
  POSTGRES_DB: storktest
  POSTGRES_USER: storktest
  POSTGRES_PASSWORD: storktest

# this is used to build docker images of stork (using DIND)
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # this is workaround for TLS problem https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/

# stages order
stages:
  - build
  - deploy

# cache
cache:
  key: one-shared-key
  paths:
  - webui/node_modules/
  - tools/

# common before script
before_script:
  - apt-get update
  - apt-get install -y wget xz-utils rake openjdk-11-jre-headless gcc g++ chromium-browser unzip
  - rake prepare_env

### build jobs ###

lint_go:
  stage: build
  script:
    - rake lint_go

unittest_backend:
  stage: build
  services:
    - name: registry.gitlab.isc.org/isc-projects/stork/ci-postgres:11
      alias: postgres
  script:
    - rake unittest_backend

ci_ui:
  stage: build
  script:
    - rake ci_ui

build_webui:
  stage: build
  script:
    - rake build_ui
  artifacts:
    name: "webui"
    expire_in: 1 week
    paths:
      - webui/dist/stork/

build_backend:
  stage: build
  script:
    - rake build_backend
  artifacts:
    name: "backend"
    expire_in: 1 week
    paths:
      - backend/cmd/stork-agent/stork-agent
      - backend/cmd/stork-server/stork-server
      - backend/cmd/stork-db-migrate/stork-db-migrate

danger:
  stage: build
  image: registry.gitlab.isc.org/isc-projects/stork/ci-danger
  before_script:
    - export CI_MERGE_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
    - export CI_PROJECT_PATH=$CI_PROJECT_ID #some version of gitlab has problems with searching by project path
    - export DANGER_GITLAB_HOST=gitlab.isc.org
    - export DANGER_GITLAB_API_BASE_URL=https://gitlab.isc.org/api/v4
  script:
    - sysctl -w net.ipv6.conf.all.disable_ipv6=1
    - sysctl -w net.ipv6.conf.default.disable_ipv6=1
    - gem install danger-commit_lint
    - danger --fail-on-errors=true --new-comment


tarball:
  stage: build
  script:
    - rake tarball
  artifacts:
    paths:
      - stork-*.tar.gz
    expire_in: 1 week


### deploy jobs ###

deploy_demo:
  stage: deploy
  when: manual
  image: docker:latest
  tags:
    - linux
    - docker
    - amd64
  services:
    - docker:dind
  dependencies:
    - build_webui
    - build_backend
  before_script:
    - ip -6 route del default
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - apk update
    - apk upgrade
    - apk add docker-compose
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STORK" | base64 -d | ssh-add -
  script:
    - docker-compose build
    - docker-compose push
    - scp -o StrictHostKeyChecking=no docker-compose.yaml jenkins@stork.lab.isc.org:~/deploy
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker-compose -f deploy/docker-compose.yaml down
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker-compose -f deploy/docker-compose.yaml up -d --no-build
