image: registry.gitlab.isc.org/isc-projects/stork/ci-base:latest

variables:
  POSTGRES_DB: storktest
  POSTGRES_USER: storktest
  POSTGRES_PASSWORD: storktest

stages:
  - build

cache:
  key: one-shared-key
  paths:
  - webui/node_modules/
  - tools/

before_script:
  - apt-get update
  - apt-get install -y wget xz-utils rake openjdk-11-jre-headless gcc g++ chromium-browser unzip
  - rake prepare_env

# race_detector:
#   stage: test
#   script:
#     - make race

# memory_sanitizer:
#   stage: test
#   script:
#     - make msan

# code_coverage:
#   stage: test
#   script:
#     - make coverage

# code_coverage_report:
#   stage: test
#   script:
#     - make coverhtml
#   only:
#   - master

lint_go:
  stage: build
  script:
    - rake lint_go

unittest_backend:
  stage: build
  services:
    - postgres:latest
  script:
    - rake unittest_backend

ci_ui:
  stage: build
  script:
    - rake ci_ui

build_webui:
  stage: build
  script:
    - rake build_ui
