version: '2.1'

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-server.txt
    # Explicitly add entries to /etc/hosts for the hosts which are connected
    # to more than two networks. These explicit entries should be added at the
    # beginning of the /etc/hosts file enforcing that the connections by hostname
    # are established with the IP addresses belonging to the storknet network.
    # Before this change, agents sometimes listened on IP addresses dedicated for
    # DHCP communication instead.
    extra_hosts:
      - "agent-kea:172.20.0.100"
      - "agent-kea6:172.20.0.106"
    image: registry.gitlab.isc.org/isc-projects/stork/server:latest
    networks:
      - storknet
    expose:
      - "8080"
    ports:
      - "8088:8080"
    environment:
      STORK_DATABASE_HOST: postgres
      STORK_DATABASE_PORT: 5432
      STORK_DATABASE_USER_NAME: stork
      STORK_DATABASE_PASSWORD: stork123
      STORK_DATABASE_NAME: stork
      STORK_ENABLE_METRICS: 1
    depends_on:
      - postgres

  agent-kea:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea.txt
    # Explicitly add entries to /etc/hosts for the hosts which are connected
    # to more than two networks. These explicit entries should be added at the
    # beginning of the /etc/hosts file enforcing that the connections by hostname
    # are established with the IP addresses belonging to the storknet network.
    # Before this change, agents sometimes listened on IP addresses dedicated for
    # DHCP communication instead.
    extra_hosts:
      - "agent-kea:172.20.0.100"
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea:latest
    hostname: agent-kea
    networks:
      storknet:
        ipv4_address: 172.20.0.100
      subnet-00:
        ipv4_address: 172.100.0.100
      subnet-01:
        ipv4_address: 172.101.0.100
      subnet-02:
        ipv4_address: 172.102.0.100
    expose:
      - "8080"  # stork server to agent
      - "9100"  # node_exporter for prometheus
      - "9547"  # kea_exporter for prometheus
    ports:
      # publish ports for development purposes
      - "8888:8080"  # port to agent
      - "9001:9001"  # port to supervisor xml-rpc
    depends_on:
      - agent-kea-mysql
      - server

  agent-kea6:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea6.txt
    # Explicitly add entries to /etc/hosts for the hosts which are connected
    # to more than two networks. These explicit entries should be added at the
    # beginning of the /etc/hosts file enforcing that the connections by hostname
    # are established with the IP addresses belonging to the storknet network.
    # Before this change, agents sometimes listened on IP addresses dedicated for
    # DHCP communication instead.
    extra_hosts:
      - "agent-kea6:172.20.0.106"
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea6:latest
    hostname: agent-kea6
    networks:
      storknet:
        ipv4_address: 172.20.0.106
      subnet6-00:
        ipv6_address: 3000:db8:1::100
      subnet6-01:
        ipv6_address: 3001:db8:1::100
    expose:
      - "8080"  # stork server to agent
      - "9547"  # kea_exporter for prometheus
    ports:
      - "8886:8080"  # publish ports for development purposes
    depends_on:
      - agent-kea6-postgres
      - server

  agent-kea-ha1:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea-ha1.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea-ha1:latest
    hostname: agent-kea-ha1
    networks:
      storknet:
        ipv4_address: 172.20.0.101
    expose:
      - "8001"
      - "9547"  # kea_exporter for prometheus
    ports:
      - "8881:8080"  # publish ports for development purposes
    depends_on:
      - server

  agent-kea-ha2:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea-ha2.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea-ha2:latest
    hostname: agent-kea-ha2
    networks:
      storknet:
        ipv4_address: 172.20.0.110
    expose:
      - "8080"
    ports:
      - "8110:8080"  # publish ports for development purposes
    depends_on:
      - server

  agent-kea-many-subnets:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea-many-subnets.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea-many-subnets:latest
    hostname: agent-kea-many-subnets
    networks:
      storknet:
        ipv4_address: 172.20.0.102
    expose:
      - "8002"
      - "9547"  # kea_exporter for prometheus
    ports:
      - "8882:8080"  # publish ports for development purposes
    depends_on:
      - server

  agent-bind9:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-bind9.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-bind9:latest
    hostname: agent-bind9
    networks:
      storknet:
        ipv4_address: 172.20.0.53
    expose:
      - "8080"
      - "9100"  # node_exporter for prometheus
      - "9119"  # bind_exporter for prometheus
    depends_on:
      - server

  agent-bind9-2:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-bind9-2.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-bind9-2:latest
    hostname: agent-bind9-2
    networks:
      storknet:
        ipv4_address: 172.20.0.54
    expose:
      - "8080"
      - "9100"  # node_exporter for prometheus
      - "9119"  # bind_exporter for prometheus
    depends_on:
      - server

  webui:
    build:
      context: .
      dockerfile: docker/docker-webui.txt
    image: registry.gitlab.isc.org/isc-projects/stork/webui:latest
    networks:
      - storknet
    ports:
      - "8080:80"
    environment:
      API_HOST: server
      API_PORT: 8080
    depends_on:
      - server

  postgres:
    image: postgres:11
    networks:
      - storknet
    environment:
      POSTGRES_USER: stork
      POSTGRES_PASSWORD: stork123
      POSTGRES_DB: stork
    ports:
      - "5678:5432"

  prometheus:
    image: prom/prometheus:v2.16.0
    networks:
      - storknet
    ports:
      - "9090:9090"
    volumes:
       - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.5.3
    networks:
      - storknet
    ports:
      - "3000:3000"
    volumes:
       - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
       - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
       - ./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
       - ./grafana/kea-dhcp4.json:/var/lib/grafana/dashboards/kea-dhcp4.json
       - ./grafana/kea-dhcp6.json:/var/lib/grafana/dashboards/kea-dhcp6.json
       - ./grafana/bind9-resolver.json:/var/lib/grafana/dashboards/bind9-resolver.json
    depends_on:
      - prometheus

  simulator:
    build:
      context: .
      dockerfile: docker/docker-simulator.txt
    # Explicitly add entries to /etc/hosts for the hosts which are connected
    # to more than two networks. These explicit entries should be added at the
    # beginning of the /etc/hosts file enforcing that the connections by hostname
    # are established with the IP addresses belonging to the storknet network.
    # Before this change, agents sometimes listened on IP addresses dedicated for
    # DHCP communication instead.
    extra_hosts:
      - "agent-kea:172.20.0.100"
      - "agent-kea6:172.20.0.106"
    image: registry.gitlab.isc.org/isc-projects/stork/dhcp-traffic:latest
    hostname: simulator
    networks:
      storknet:
        ipv4_address: 172.20.0.200
      subnet-00:
        ipv4_address: 172.100.0.200
      subnet-01:
        ipv4_address: 172.101.0.200
      subnet-02:
        ipv4_address: 172.102.0.200
      subnet6-00:
        ipv6_address: 3000:db8:1::200
      subnet6-01:
        ipv6_address: 3001:db8:1::200
    ports:
      - "5000:5000"
    depends_on:
      - server

  agent-kea-mysql:
    image: mysql:5.7
    restart: always
    networks:
      storknet:
        ipv4_address: 172.20.0.115
    environment:
      MYSQL_ROOT_PASSWORD: kea
      MYSQL_DATABASE: kea
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea

  agent-kea6-postgres:
    image: postgres:11
    restart: always
    networks:
      storknet:
        ipv4_address: 172.20.0.116
    environment:
      POSTGRES_USER: kea
      POSTGRES_PASSWORD: kea
      POSTGRES_DB: kea
    ports:
      - "6789:5432"

volumes:
  db-data:
  web-data:

networks:
  storknet:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
        - subnet: 3009:db8:1::/64
  subnet-00:
    ipam:
      config:
        - subnet: 172.100.0.0/24
  subnet-01:
    ipam:
      config:
        - subnet: 172.101.0.0/24
  subnet-02:
    ipam:
      config:
        - subnet: 172.102.0.0/24
  subnet6-00:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 3000:db8:1::/64
  subnet6-01:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 3001:db8:1::/64
