version: '3'

services:
  server:
    restart: always
    build:
      context: backend
      dockerfile: docker-server.txt
    expose:
      - "8080"
    ports:
      - "8088:8080"
    environment:
      DB_URL: "postgresql://stork:stork123@postgres:5432/stork"
    depends_on:
      - postgres

  webui:
    build:
      context: webui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      API_HOST: server
      API_PORT: 8080
    depends_on:
      - server

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: stork
      POSTGRES_PASSWORD: stork123
      POSTGRES_DB: stork

volumes:
  db-data:
  web-data:
