version: '3'

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-server.txt
    image: registry.gitlab.isc.org/isc-projects/stork/server:latest
    expose:
      - "8080"
    ports:
      - "8088:8080"
    environment:
      STORK_DATABASE_HOST: postgres
      STORK_DATABASE_PORT: 5432
      STORK_DATABASE_USER_NAME: stork
      STORK_DATABASE_PASSWORD: stork123
      STORK_DATABASE_NAME: stork
    depends_on:
      - postgres

  agent-kea:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea:latest
    hostname: agent-kea
    expose:
      - "8080"

  agent-bind9:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-bind9.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-bind9:latest
    hostname: agent-bind9
    expose:
      - "8080"

  webui:
    build:
      context: .
      dockerfile: docker/docker-webui.txt
    image: registry.gitlab.isc.org/isc-projects/stork/webui:latest
    ports:
      - "8080:80"
    environment:
      API_HOST: server
      API_PORT: 8080
    depends_on:
      - server

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: stork
      POSTGRES_PASSWORD: stork123
      POSTGRES_DB: stork

volumes:
  db-data:
  web-data:
