  Settings:
    type: object
    properties:
      bind9_stats_puller_interval:
        type: integer
      kea_stats_puller_interval:
        type: integer
      kea_hosts_puller_interval:
        type: integer
      grafana_url:
        type: string
      prometheus_url:
        type: string
