  Settings:
    type: object
    properties:
      bind9_stats_puller_interval:
        type: integer
      grafana_url:
        type: string
      kea_hosts_puller_interval:
        type: integer
      kea_stats_puller_interval:
        type: integer
      kea_status_puller_interval:
        type: integer
      apps_state_puller_interval:
        type: integer
      prometheus_url:
        type: string
      metrics_collector_interval:
        type: integer

  Puller:
    type: object
    properties:
      name:
        type: string
        readOnly: true
      setting:
        type: string
        readOnly: true
      interval:
        type: integer
        readOnly: true
      lastExecutedAt:
        type: string
        format: date-time
        readOnly: true

  Pullers:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Puller'
      total:
        type: integer
