---
swagger: "2.0"
info:
  description: An API for Stork
  title: Stork API
  version: 0.1.0
schemes:
- http
basePath: /api


paths:
  /version:
    get:
      responses:
        200:
          description: Version of Stork
          schema:
            $ref: "#/definitions/Version"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /agents/{agentIp}/version:
    get:
      summary: Get agent's version.
      operationId: getAgentVersion
      parameters:
        - in: path
          name: agentIp
          type: string
          required: true
          description: IP address of agent.
      responses:
        200:
          description: Agent's version
          schema:
            $ref: "#/definitions/AgentVersion"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"


definitions:
  Version:
    type: object
    required:
      - version
      - date
      - type
    properties:
      version:
        type: string
      date:
        type: string
        format: date-time
      type:
        type: string
        enum: [stable, release-candidate, development]

  AgentVersion:
    type: object
    required:
      - version
    properties:
      version:
        type: string

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
